// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajProjesi.Areas.Data;

#nullable disable

namespace StajProjesi.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230809230046_StudentInfoTable")]
    partial class StudentInfoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StajProjesi.Models.StudentInfo", b =>
                {
                    b.Property<string>("StId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Gno")
                        .HasColumnType("float");

                    b.Property<string>("StEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StId");

                    b.ToTable("StudentInfos");

                    b.HasData(
                        new
                        {
                            StId = "100200300",
                            Bolum = "Bilgisayar Mühendisliği",
                            Gno = 3.0099999999999998,
                            StEmail = "ozge@ogr.edu.tr",
                            StName = "Özge Kurnaz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
