// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajProjesi.Areas.Data;

#nullable disable

namespace StajProjesi.Migrations.Classes1Db
{
    [DbContext(typeof(Classes1DbContext))]
    partial class Classes1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StajProjesi.Models.SecondTerm", b =>
                {
                    b.Property<string>("Classname")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Bütünleme")
                        .HasColumnType("int");

                    b.Property<int>("FinalNt")
                        .HasColumnType("int");

                    b.Property<int>("Vize")
                        .HasColumnType("int");

                    b.HasKey("Classname");

                    b.ToTable("Secondt");

                    b.HasData(
                        new
                        {
                            Classname = "Bilgisayar Ağları",
                            Bütünleme = 0,
                            FinalNt = 40,
                            Vize = 90
                        },
                        new
                        {
                            Classname = "Sistem Analizi ve Tasarımı",
                            Bütünleme = 0,
                            FinalNt = 83,
                            Vize = 60
                        },
                        new
                        {
                            Classname = "Web Tabanlı Programlama",
                            Bütünleme = 0,
                            FinalNt = 80,
                            Vize = 52
                        },
                        new
                        {
                            Classname = "Mesleki İngilizce IV",
                            Bütünleme = 0,
                            FinalNt = 77,
                            Vize = 73
                        },
                        new
                        {
                            Classname = "Veri Tabanı Yönetim Sistemleri II",
                            Bütünleme = 72,
                            FinalNt = 37,
                            Vize = 43
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
